packages:
  - "packages/*"
  - "services/*"
  - "apps/*"

overrides:
  "@noble/hashes": 1.8.0
  "@noble/curves": 1.9.2
  "@noble/ciphers": 1.2.1

allowBuilds:
  bufferutil: false
  esbuild: true
  keccak: false
  utf-8-validate: false
